/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    phone?: any;
    /**
     * User Status
     * @type {number}
     * @memberof User
     */
    userStatus?: any;
}
